scrape_configs:
  - job_name: 'spring-micrometer-prometheus-grafana'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s # This can be adjusted based on our needs
    static_configs:
      - targets: ['spring-micrometer-prometheus-grafana:8080']