---
version: '3.8'
services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maxlogic
    ports:
      - 5432:5432