version: '3.3'
services:    
            
    tutorial-mongo-database:
        image: mongo:4.0.13
        container_name: tutorial-mongo            
        ports:
            - '27017:27017'
        networks:
            - tutorial
        volumes:
            - ./mongodb-startupscripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
            - tutorial-data:/data/tutorial-db
            - tutorial-data:/data/tutorial-db/configdb
            
volumes:
    tutorial-data:
        external: true
        
networks:
    tutorial:
        driver: overlay