/*
*	For Oracle database - To create initial database tables required to run example.
*/


--Create Table EMPLOYEE
CREATE TABLE EMPLOYEE
(
	EMP_ID NUMBER(10) NOT NULL,
	EMP_NAME VARCHAR2(10),
	EMP_SALARY NUMBER,
	EMP_MANAGER_ID NUMBER(10),
	EMP_GRADE CHAR(1),
	CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMP_ID)
);

CREATE SEQUENCE EMP_SEQ
	MINVALUE 1
	MAXVALUE 10000
	START WITH 1
	INCREMENT BY 1
	NOCACHE;
	
INSERT INTO EMPLOYEE
	(EMP_ID, EMP_NAME, EMP_SALARY, EMP_GRADE)
	VALUES
	(EMP_SEQ.NEXTVAL, 'Sourabh', 500000, 'A');

UPDATE EMPLOYEE
	SET EMP_NAME='Sourabh', EMP_SALARY=1000000, EMP_GRADE='A'
	WHERE EMP_ID = 1;